id: I99CFFE7F
legacy_id: P005450
ocr_import_info:
  bdrc_scan_id: W1KG17280
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T21:21:47'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T09:34:42.131883+00:00'
last_modified: 2022-08-31 17:35:10.683864
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG17280
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG17280
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གེ་སར་འཇང་གླིང་དང་ཁ་གླིང་།
statistics:
  ocr_word_mean_confidence_index: 0.7605755901815411
  ocr_word_median_confidence_index: 0.8199999928474426
quality: null
bases:
  I1KG17414:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG17414
      total_pages: 412
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG17414.txt
    statistics:
      ocr_word_median_confidence_index: 0.8500000238418579
      ocr_word_mean_confidence_index: 0.7945780515811612
    legacy_id: v001
  I1KG17415:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG17415
      total_pages: 390
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG17415.txt
    statistics:
      ocr_word_median_confidence_index: 0.7799999713897705
      ocr_word_mean_confidence_index: 0.7253211794186668
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
