id: I99CFFE7F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T21:24:07+00:00'
last_modified: '2022-06-08T03:10:23.089094+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG17280
  title: གེ་སར་འཇང་གླིང་དང་ཁ་གླིང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    B637:
      image_group_id: I1KG17414
      title: ''
      total_pages: 412
      order: 1
      base_file: B637.txt
    BB1C:
      image_group_id: I1KG17415
      title: ''
      total_pages: 390
      order: 2
      base_file: BB1C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
